## 1. 科学计算神器 Numpy
1. 容器特性
2. 算法特性

In [2]:
import numpy as np


arr1 = np.array([1, 2, 3, 4, 5])

In [3]:
# 维度信息
arr1.ndim

1

In [4]:
# 形状，每个维度上有几个数字
arr1.shape

(5,)

In [5]:
arr1.dtype

dtype('int64')

In [6]:
arr1.size

5

In [7]:
x = np.random.randint(low=0,high=101,size=(20,70))

In [8]:
x.shape

(20, 70)

In [10]:
x[4,:]

array([ 42,  75,  56,  47,  43,  41,  66,   5,  16,  61,  27,  68,  63,
        86,   2,  37,  39,  68,  40,  39,  59,  86,  18,   0,  44, 100,
        13,  12,  29,  29,  89,  89,  32,  76,  90,  36,  98,  79,  34,
         5,  23,  15,  80,  90,  43,  89,  55,   6,  13,  77,  50,  14,
        12,  12,  30,  46,  92,  98,  12,  15,  71,  34,  12,  17,  69,
        74,   4,   9,  50,  19])

In [ ]:
# 中心话 x-x.means()
# 归一化 把所有的数据线性映射到[0,1]之间 (x-x.min())/(x.max() - x.min())
# 标准化 (x-x.means())/x.std, 以0为中心，以1为标准差

## 数据的预处理
1. 特征和标签都需要预处理，一般来说，只需要处理特征值即可（特别是分类任务）
2. 训练集和测试机需要做**一模一样**的预处理
3. 预处理需要的参数，从训练集中去提取

In [11]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


# load data
X, y = load_iris(return_X_y=True)

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
# cal metrics

_max = X_train.max(axis=0)
_min = X_train.min(axis=0)
_mean = X_train.mean(axis=0)
_std = X_train.std(axis=0)

In [13]:
_max

array([7.7, 4.4, 6.7, 2.5])

In [14]:
_min

array([4.3, 2. , 1. , 0.1])

In [15]:
_std

array([0.82036535, 0.44724776, 1.74502786, 0.74914766])

In [16]:
_mean

array([5.80916667, 3.06166667, 3.72666667, 1.18333333])

In [21]:
# decentralization

X_train_cen = X_train - _mean
X_test_cen = X_test - _mean

In [18]:
# normalization



array([[-1.20916667,  0.53833333, -2.72666667, -0.98333333],
       [-0.10916667,  1.33833333, -2.22666667, -0.78333333],
       [ 0.89083333,  0.03833333,  0.67333333,  0.21666667],
       [-1.00916667,  0.33833333, -2.12666667, -0.98333333],
       [-1.40916667,  0.13833333, -2.42666667, -0.98333333],
       [ 0.49083333, -0.56166667,  1.27333333,  0.71666667],
       [ 0.59083333,  0.13833333,  0.77333333,  0.31666667],
       [-0.60916667,  0.43833333, -2.22666667, -0.98333333],
       [-0.80916667,  0.53833333, -2.32666667, -0.98333333],
       [-0.60916667,  1.03833333, -2.22666667, -1.08333333],
       [-0.00916667, -0.36166667,  1.37333333,  0.71666667],
       [ 0.19083333,  0.33833333,  0.77333333,  0.41666667],
       [ 0.89083333,  0.03833333,  0.97333333,  0.31666667],
       [-0.40916667,  0.83833333, -2.42666667, -0.78333333],
       [-0.40916667,  0.63833333, -2.22666667, -0.98333333],
       [-0.30916667, -0.66166667, -0.02666667, -0.18333333],
       [ 0.49083333, -0.

In [19]:
X_train

array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2

In [1]:
import torch

In [2]:
tensor = torch.tensor(data=[1, 2, 3, 4, 5])

In [3]:
tensor

tensor([1, 2, 3, 4, 5])

In [4]:
tensor.shape

torch.Size([5])

In [6]:
tensor.size()

torch.Size([5])

In [7]:
tensor.ndim

1

In [8]:
torch.randint(low=0, high=2, size=(5,))

tensor([0, 0, 0, 0, 0])

In [9]:
torch.randint(low=0, high=100,size=(2,3))

tensor([[24, 92, 71],
        [32, 30, 52]])

In [10]:
torch.randn(3,5)

tensor([[ 0.4037, -0.3144,  0.2767, -0.2501,  0.4862],
        [-0.0830, -1.1668, -1.8655, -0.7176,  1.7660],
        [ 0.3652, -1.0812,  0.4856,  0.0619,  0.2566]])

In [11]:
a = torch.randn(5)

In [12]:
a

tensor([-1.1190,  0.9012, -1.3635, -2.0695,  0.3172])

In [15]:
b = torch.randn(5)

In [16]:
b

tensor([-0.6946, -0.1627, -0.9921, -0.7152,  0.3539])

In [17]:
a + b

tensor([-1.8136,  0.7385, -2.3556, -2.7848,  0.6711])

In [18]:
a - b

tensor([-0.4244,  1.0639, -0.3714, -1.3543, -0.0368])

In [21]:
torch.concatenate((a, b),dim=0)

tensor([-1.1190,  0.9012, -1.3635, -2.0695,  0.3172, -0.6946, -0.1627, -0.9921,
        -0.7152,  0.3539])