## 创建numpy ndarray

In [1]:
import numpy as np


x = [1, 2, 3]
x = np.array(x)

In [3]:
x

array([1, 2, 3])

## numpy ndarray常用属性
* shape
* ndim
* dtype
* size

In [4]:
x.shape

(3,)

In [5]:
x.ndim

1

In [6]:
x.size

3

In [7]:
x.dtype

dtype('int64')

In [9]:
y = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
y.ndim

2

In [11]:
y.size

6

In [12]:
y.shape

(2, 3)

## 强制类型统一
numpy设计初衷是用于运算的，所以对数据类型进行统一优化<br>
**注意**：
1. numpy默认ndarray的所有元素类型是相同的
2. 如果传进来的列表中包含不同的类型，则强制统一为同一类型，优先级为**str>float>int**

## 使用numpy routines函数创建数组

In [16]:
np.linspace(0,100,11,dtype=int) #生成一个顺序的等差数列

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [17]:
np.arange(stop=5,start=0,step=1,dtype=int)

array([0, 1, 2, 3, 4])

In [20]:
np.random.randint(low=0, high=101, size=(5,2))

array([[33, 57],
       [30, 72],
       [99, 33],
       [40, 21],
       [27, 83]])

In [26]:
np.random.randn(3,2,2)

array([[[ 0.11222811,  0.48054412],
        [ 0.01039108, -0.44457419]],

       [[-0.98733223,  0.6354508 ],
        [ 1.3350954 ,  1.10076863]],

       [[ 0.51928274,  0.18825551],
        [-1.50526183,  1.42941689]]])

In [33]:
x = np.random.randint(low=0, high=10, size=(5,))

In [34]:
x

array([2, 0, 8, 9, 9])

In [35]:
x[0]

2

In [36]:
x[0:3]

array([2, 0, 8])

In [37]:
x[[0,2]]

array([2, 8])